### ISSUE TITLE
UUID Datatype

### ISSUE THREAD

**Issue by TheSerumDev** [cadenzauk/siesta#5]
This is my first time working with the framework. My question is, is there a way to change the SQL type for UUIDs? Currently it is stored as BINARY(16) in Mariadb, but what if we want to use Varchar for debug purposes? If I use VARCHAR(36) for UUIDs the framework will be generated wrong values.

**Comment by mdrodg** [comment]
You should be able to do what you want by registering a type adapter.

```
Database database = Database.newBuilder()
    ...
    .type(UUID.class, DbTypeId.UUID, new DbTypeAdapter<>(DbTypeId.VARCHAR, UUID::toString, UUID::fromString))
    .build();
```

**Comment by TheSerumDev** [comment]
wellp it works thank you for the answer, could you maybe answer to my other question (https://github.com/cadenzauk/siesta/issues/6) ?

**Comment by TheSerumDev** [comment]
wellp it works thank you for the answer, could you maybe answer to my other question (https://github.com/cadenzauk/siesta/issues/6) ?
